language: python

python:
  - "3.6"

install:
  - pip install -r requirements.txt
  - python setup.py -q install

script:
  - pytest --cov=src --cov-config=.coveragerc tests

after_success:
  - codecov
